image: ${CI_REGISTRY}/traque/ont-docker-base/ont-base-python:3.12

include:
    - project: "epi2melabs/ci-templates"
      file:
          - "push-github.yaml"
          - "push-conda.yaml"
          - "snippets.yaml"

stages:
    - test
    - build
    - release

.setup_ubuntu: &setup_ubuntu |
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y -qq build-essential curl git wget


test-all:
    stage: test
    before_script:
        - *setup_ubuntu
        - apt-get install -y -qq libbz2-dev libcurl4-gnutls-dev liblzma-dev libncurses5-dev libssl-dev zlib1g-dev  
    script:
        - make -j 4 install
        - make test

build:sdist:
    stage: build
    script:
        - make sdist
    artifacts:
        paths:
            - dist/*.tar.gz
            - dist/*.whl

deploy:pypi:
    stage: release
    script:
        - make venv_pypi/bin/activate
        - source venv_pypi/bin/activate
        - twine upload --non-interactive dist/pomoxis*
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/'


#########
# CONDA #
#########

conda:
    extends: .deploy-conda
    stage: build
    variables:
        UPLOAD: "no"
        USE_ORG_CHANNEL: "yes"
        CONDA_PKG: "${CI_PROJECT_NAME}"
        PACKAGE_ARCH: "noarch"
        CONDA_PKG_VERSION: "dev"
    before_script:
        - cd conda
    rules:
        - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(\S+)?$/
          when: never
        - if: $CI_PIPELINE_SOURCE == "push"

push-conda:
    extends: .deploy-conda
    variables:
        USE_ORG_CHANNEL: "yes"
        CONDA_PKG: "${CI_PROJECT_NAME}"
        CONDA_PKG_VERSION: ${CI_COMMIT_TAG}
    before_script:
        - cd conda
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(\S+)?$/'
